/****************************************************************
 *  
 * 
 */

export const APP_SOCKET_ERROR = 'APP_SOCKET_ERROR';

export const APP_SOCKET_CONNECT= 'APP_SOCKET_CONNECT';
export const APP_SOCKET_DISCONNECT = 'APP_SOCKET_DISCONNECT';

export const APP_SOCKET_JOIN_ROOM = 'APP_SOCKET_JOIN_ROOM';
export const APP_SOCKET_LEAVE_ROOM = 'APP_SOCKET_LEAVE_ROOM';

// admin send command , other receives 
export const APP_SOCKET_SEND_COMMAND_MESSAGE = "APP_SOCKET_SEND_COMMAND_MESSAGE";
export const APP_SOCKET_RECEIVED_COMMAND_MESSAGE = "APP_SOCKET_RECEIVED_COMMAND_MESSAGE";

// message 
export const APP_SOCKET_CHAT_MESSAGE = "APP_SOCKET_CHAT_MESSAGE";
export const APP_SOCKET_QA_MESSAGE = "APP_SOCKET_QA_MESSAGE";

// poll
export const APP_SOCKET_POLL_START_MESSAGE = "APP_SOCKET_POLL_START_MESSAGE";
export const APP_SOCKET_POLL_END_MESSAGE = "APP_SOCKET_POLL_END_MESSAGE";


